weights: ../resource/best.pt
cfg: ''
data: ../resource/roboflow/dataset/data.yaml
hyp:
  lr0: 0.00334
  lrf: 0.15135
  momentum: 0.74832
  weight_decay: 0.00025
  warmup_epochs: 3.3835
  warmup_momentum: 0.59462
  warmup_bias_lr: 0.18657
  box: 0.02
  cls: 0.21638
  cls_pw: 0.5
  obj: 0.51728
  obj_pw: 0.67198
  iou_t: 0.2
  anchor_t: 3.3744
  fl_gamma: 0.0
  hsv_h: 0.01041
  hsv_s: 0.54703
  hsv_v: 0.27739
  degrees: 0.0
  translate: 0.04591
  scale: 0.75544
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 0.85834
  mixup: 0.04266
  copy_paste: 0.0
  anchors: 3.412
epochs: 100
batch_size: 6
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: ASL
name: fine-tuning
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: ASL/fine-tuning7
